### ISSUE TITLE
Image doesn't show up

### ISSUE THREAD

**Issue by chamilad** [zagortenay333/jelly-conky#1]
Hi,

I've followed the README instructions and started conky through the Terminal, however the image doesn't seem to appear.

There is an error message on the Conky output.

![image](https://cloud.githubusercontent.com/assets/505989/14761357/71eeb41e-097c-11e6-93de-6376d1f96071.png)

**Comment by zagortenay333** [comment]
What version of conky are you running?

**Comment by chamilad** [comment]
`conky -v` gives 1.10.1.

**Comment by zagortenay333** [comment]
Did you try installing `conky-all` ?

**Comment by chamilad** [comment]
Thanks! That was the issue. I had only installed `conky`.
