### ISSUE TITLE
unkown variable $image

### ISSUE THREAD

**Issue by JosephKah** [zagortenay333/jelly-conky#3]
Hi,
great looking conky!
I have got an issue with the clock--date--weather__small conky.rc:

conky: desktop window (1200015) is subwindow of root window (f9)
conky: window type - normal
conky: drawing to created window (0x2400002)
conky: drawing to double buffer
conky: Unknown setting 'imlib_cache_size'
conky: unknown variable '$image'
conky: forked to background, pid is 31971

The visible consequence is a rendered text
${image}
as a last line on the desktop.
Everything else renders fine.

I tried to edit the conkyrcs last line (deleting, renaming
![conky_render](https://cloud.githubusercontent.com/assets/18646203/14769069/b21b04b4-0a50-11e6-8523-fe601e25d911.png)
) but failed so far.

**Comment by zagortenay333** [comment]
Are you kidding me? There is only one issue opened against this project, and you managed to duplicate it. #1 
:smile:

**Comment by JosephKah** [comment]
Sorry, I really didn't saw that - I am new to GitHub :-(

**Comment by zagortenay333** [comment]
No problem :+1:
