### ISSUE TITLE
Weather not appearing

### ISSUE THREAD

**Issue by j4media** [zagortenay333/jelly-conky#4]
Great Conky!  I have it installed on Manjaro KDE.  Time and date appear fine, but weather does not appear at all.  All I get is the 'degree' marks with no numbers or icons.  I entered my API key and city code as per your instructions.  Here is my terminal output:  I double checked that the .jelly-conky-icons is indeed in my home directory.

conky: desktop window (2000012) is subwindow of root window (49d)
conky: window type - normal
conky: drawing to created window (0x5a00002)
conky: drawing to double buffer
conky: forked to background, pid is 27926
[john@linux ~]$ 
sh: jq: command not found
sh: jq: command not found
sh: jq: command not found
sh: jq: command not found
sh: jq: command not found
cp: cannot stat '/home/john/.jelly-conky-icons/#fff__64/.png': No such file or directory
conky: Unable to load image '/home/john/.cache/current.png'

**Comment by j4media** [comment]
Ignore issue, my bad.  I didn't have JQ installed.  Once I installed it everything worked fine :)

Can you tell me how I change the time to 12 hour with am/pm and actually get the city name to appear in the Conky?  Thanks!

**Comment by zagortenay333** [comment]
Play around with the conky and you'll figure out how to add the city name.
