### ISSUE TITLE
not working: imlib2 developer warning

### ISSUE THREAD

**Issue by rhoconlinux** [zagortenay333/jelly-conky#6]
Hi there, just installed and can't run it. Conky is angry about some library. 

`Conky: /home/rho/.conkyrc: 1: no such configuration: 'conky.config'
Conky: /home/rho/.conkyrc: 3: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 4: no such configuration: '--'
Conky: /home/rho/.conkyrc: 5: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 6: no such configuration: 'background=true,'
Conky: /home/rho/.conkyrc: 7: no such configuration: 'update_interval=1,'
Conky: /home/rho/.conkyrc: 8: no such configuration: 'double_buffer=true,'
Conky: /home/rho/.conkyrc: 9: no such configuration: 'no_buffers=true,'
Conky: /home/rho/.conkyrc: 10: no such configuration: 'imlib_cache_size=10,'
Conky: /home/rho/.conkyrc: 12: no such configuration: 'draw_shades=false,'
Conky: /home/rho/.conkyrc: 13: no such configuration: 'draw_outline=false,'
Conky: /home/rho/.conkyrc: 14: no such configuration: 'draw_borders=false,'
Conky: /home/rho/.conkyrc: 17: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 18: no such configuration: '--'
Conky: /home/rho/.conkyrc: 19: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 20: no such configuration: 'gap_x=100,'
Conky: /home/rho/.conkyrc: 21: no such configuration: 'gap_y=70,'
Conky: /home/rho/.conkyrc: 23: no such configuration: 'minimum_height=250,'
Conky: /home/rho/.conkyrc: 24: no such configuration: 'minimum_width=360,'
Conky: /home/rho/.conkyrc: 26: no such configuration: 'own_window=true,'
Conky: /home/rho/.conkyrc: 27: no such configuration: 'own_window_type="normal",'
Conky: /home/rho/.conkyrc: 28: no such configuration: 'own_window_transparent=true,'
Conky: /home/rho/.conkyrc: 29: no such configuration: 'own_window_hints="undecorated,below,sticky,skip_taskbar,skip_pager",'
Conky: /home/rho/.conkyrc: 31: no such configuration: 'own_window_argb_visual=true,'
Conky: /home/rho/.conkyrc: 32: no such configuration: 'own_window_argb_value=0,'
Conky: /home/rho/.conkyrc: 35: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 36: no such configuration: '--'
Conky: /home/rho/.conkyrc: 37: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 38: no such configuration: 'use_xft=true,'
Conky: /home/rho/.conkyrc: 39: no such configuration: 'xftalpha=1,'
Conky: /home/rho/.conkyrc: 40: no such configuration: 'font="Droid'
Conky: /home/rho/.conkyrc: 41: no such configuration: 'text_buffer_size=256,'
Conky: /home/rho/.conkyrc: 42: no such configuration: 'override_utf8_locale=true,'
Conky: /home/rho/.conkyrc: 45: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 46: no such configuration: '--'
Conky: /home/rho/.conkyrc: 47: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 48: no such configuration: 'default_color="FFFFFF",'
Conky: /home/rho/.conkyrc: 50: no such configuration: 'color0="FFFFFF",'
Conky: /home/rho/.conkyrc: 51: no such configuration: 'color1="FFFFFF",'
Conky: /home/rho/.conkyrc: 52: no such configuration: 'color2="FFFFFF",'
Conky: /home/rho/.conkyrc: 53: no such configuration: 'color3="FFFFFF",'
Conky: /home/rho/.conkyrc: 54: no such configuration: 'color4="FFFFFF",'
Conky: /home/rho/.conkyrc: 55: no such configuration: 'color5="FFFFFF",'
Conky: /home/rho/.conkyrc: 56: no such configuration: 'color6="FFFFFF",'
Conky: /home/rho/.conkyrc: 57: no such configuration: 'color7="FFFFFF",'
Conky: /home/rho/.conkyrc: 58: no such configuration: 'color8="FFFFFF",'
Conky: /home/rho/.conkyrc: 59: no such configuration: 'color9="FFFFFF",'
Conky: /home/rho/.conkyrc: 62: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 63: no such configuration: '--'
Conky: /home/rho/.conkyrc: 64: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 65: no such configuration: 'template0="~/.jelly-conky-icons/'
Conky: /home/rho/.conkyrc: 68: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 69: no such configuration: '--'
Conky: /home/rho/.conkyrc: 70: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 71: no such configuration: 'template6="",'
Conky: /home/rho/.conkyrc: 74: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 75: no such configuration: '--'
Conky: /home/rho/.conkyrc: 76: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 77: no such configuration: 'template7="",'
Conky: /home/rho/.conkyrc: 80: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 81: no such configuration: '--'
Conky: /home/rho/.conkyrc: 82: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 83: no such configuration: 'template8="metric",'
Conky: /home/rho/.conkyrc: 86: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 87: no such configuration: '--'
Conky: /home/rho/.conkyrc: 88: no such configuration: '--'
Conky: /home/rho/.conkyrc: 89: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 90: no such configuration: 'template9=""'
Conky: /home/rho/.conkyrc: 92: no such configuration: '}'
Conky: /home/rho/.conkyrc: 95: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 96: no such configuration: '-------------------------------------'
Conky: /home/rho/.conkyrc: 99: no such configuration: 'conky.text'
Conky: /home/rho/.conkyrc: 100: no such configuration: '\'
Conky: /home/rho/.conkyrc: 101: no such configuration: '\'
Conky: /home/rho/.conkyrc: 102: no such configuration: '${execi'
Conky: /home/rho/.conkyrc: 103: no such configuration: '${execi'
Conky: /home/rho/.conkyrc: 104: no such configuration: '\'
Conky: /home/rho/.conkyrc: 105: no such configuration: '\'
Conky: /home/rho/.conkyrc: 106: no such configuration: '\'
Conky: /home/rho/.conkyrc: 107: no such configuration: '\'
Conky: /home/rho/.conkyrc: 108: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 109: no such configuration: '${alignc}${time'
Conky: /home/rho/.conkyrc: 110: no such configuration: '\'
Conky: /home/rho/.conkyrc: 111: no such configuration: '\'
Conky: /home/rho/.conkyrc: 112: no such configuration: '\'
Conky: /home/rho/.conkyrc: 113: no such configuration: '\'
Conky: /home/rho/.conkyrc: 114: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 115: no such configuration: '\'
Conky: /home/rho/.conkyrc: 116: no such configuration: '\'
Conky: /home/rho/.conkyrc: 117: no such configuration: '\'
Conky: /home/rho/.conkyrc: 118: no such configuration: '\'
Conky: /home/rho/.conkyrc: 119: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 120: no such configuration: '${time'
Conky: /home/rho/.conkyrc: 121: no such configuration: '\'
Conky: /home/rho/.conkyrc: 122: no such configuration: '\'
Conky: /home/rho/.conkyrc: 123: no such configuration: '\'
Conky: /home/rho/.conkyrc: 124: no such configuration: '\'
Conky: /home/rho/.conkyrc: 125: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 126: no such configuration: '${voffset'
Conky: /home/rho/.conkyrc: 127: no such configuration: '\'
Conky: /home/rho/.conkyrc: 128: no such configuration: '\'
Conky: /home/rho/.conkyrc: 129: no such configuration: '\'
Conky: /home/rho/.conkyrc: 130: no such configuration: '\'
Conky: /home/rho/.conkyrc: 131: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 132: no such configuration: '${alignc}${execi'
Conky: /home/rho/.conkyrc: 133: no such configuration: '\'
Conky: /home/rho/.conkyrc: 134: no such configuration: '\'
Conky: /home/rho/.conkyrc: 135: no such configuration: '\'
Conky: /home/rho/.conkyrc: 136: no such configuration: '\'
Conky: /home/rho/.conkyrc: 137: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 138: no such configuration: '${alignc}${execi'
Conky: /home/rho/.conkyrc: 139: no such configuration: '\'
Conky: /home/rho/.conkyrc: 140: no such configuration: '\'
Conky: /home/rho/.conkyrc: 141: no such configuration: '\'
Conky: /home/rho/.conkyrc: 142: no such configuration: '\'
Conky: /home/rho/.conkyrc: 143: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 144: no such configuration: '${goto'
Conky: /home/rho/.conkyrc: 145: no such configuration: '${execi'
Conky: /home/rho/.conkyrc: 146: no such configuration: '\'
Conky: /home/rho/.conkyrc: 147: no such configuration: '\'
Conky: /home/rho/.conkyrc: 148: no such configuration: '\'
Conky: /home/rho/.conkyrc: 149: no such configuration: '\'
Conky: /home/rho/.conkyrc: 150: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 151: no such configuration: '${goto'
Conky: /home/rho/.conkyrc: 152: no such configuration: '${color7}${execi'
Conky: /home/rho/.conkyrc: 153: no such configuration: '${color8}${execi'
Conky: /home/rho/.conkyrc: 154: no such configuration: '\'
Conky: /home/rho/.conkyrc: 155: no such configuration: '\'
Conky: /home/rho/.conkyrc: 156: no such configuration: '\'
Conky: /home/rho/.conkyrc: 157: no such configuration: '\'
Conky: /home/rho/.conkyrc: 158: no such configuration: '${font'
Conky: /home/rho/.conkyrc: 159: no such configuration: '${goto'
Conky: /home/rho/.conkyrc: 160: no such configuration: '${execi'
Conky: /home/rho/.conkyrc: 161: no such configuration: '\'
Conky: /home/rho/.conkyrc: 162: no such configuration: '\'
Conky: /home/rho/.conkyrc: 163: no such configuration: '\'
Conky: /home/rho/.conkyrc: 164: no such configuration: '\'
Conky: /home/rho/.conkyrc: 165: no such configuration: '${execi'
Conky: /home/rho/.conkyrc: 166: no such configuration: ']]'
Conky: missing text block in configuration; exiting
***** Imlib2 Developer Warning ***** :
	This program is calling the Imlib call:
	imlib_context_free();
	With the parameter:
	context
	being NULL. Please fix your program.
`

any ideas?
Running on Freya, Conky 1.9, installed conky-all.

**Comment by zagortenay333** [comment]
Are you using the correct version of this theme? I.e. this one: https://github.com/zagortenay333/jelly-conky/releases

**Comment by rhoconlinux** [comment]
Indeed! That was the problem. 
It is working now, thank you man! :D :dancer:
