### ISSUE TITLE
No weather icon shown

### ISSUE THREAD

**Issue by AceThaGemini** [zagortenay333/jelly-conky#7]
Copy `.conky_weather_icons` folder in `~`: :heavy_check_mark: 
All fonts are installed `Roboto, Roboto Thin` and `Droid Sans` fonts. :heavy_check_mark:
But still, instead of showing a weather icon, a text `${image}` is shown. :frowning_face:  

![screenshot from 2017-07-01 12-25-45](https://user-images.githubusercontent.com/18669218/27760912-3a41eace-5e5b-11e7-9eb1-209e925b7701.png)

I've used a `.conkyrc` theme file from the folder `clock--date--weather_big`. 

I've only edited the parts `gap_x`, `gap_y` for positioning, `template6` for API key and `template7` for City ID as instructed.

`conky.config = {`
#####  Icon Sources part
`template0="~/.jelly-conky-icons/#fff__64",`
##### The text part for icon
`conky.text = [[`
###   ... .. .
`${execi 300 cp -f ${template0}/$(jq .weather[0].id ~/.cache/weather.json).png` `~/.cache/current.png}${image ~/.cache/current.png -p 236,140 -s 64x64}\`
`]]`

**Comment by zagortenay333** [comment]
Forgot about this issue. Your conky version doesn't recognize the image variable. If you are on ubuntu you probably have to install `conky-all`.

**Comment by AceThaGemini** [comment]
Installing `conky-all` solved the prob. Seems like not only on Ubuntu, also on its derivatives. I'm on Mint, just for the record.
Thanks @zagortenay333

**Comment by zagortenay333** [comment]
Cheers.
